### ISSUE TITLE
Doesn't work with symlinked iTerm.app

### ISSUE THREAD

**Issue by spry-rproud** [vitorgalvao/custom-iterm-applescripts-for-alfred#15] opened 2015-09-15 12:56 UTC
This doesn't seem to work with iTerm not installed at the default location.  I'm not positive this is the reason, but taking a quick look through the 2.1.1 script and it's my first assumption (any logs or output I can check to verify?).  I have installed iTerm 2 with Cask and this doesn't seem to work with your lastpass workflow.  Is there a way to "find" an application before trying to send it commands, or at least use a symlink in the Applications folder to find it?

**Comment by stuartcryan** [comment] 2015-09-18 03:18
Hi Ryan,
In the actual code there is an inline comment stating:
-- Please note, if you store the iTerm binary in any other location than the Applications Folder
-- please ensure you update the two locations below (in the format of : rather than / for folder dividers)
-- this gets around issues with AppleScript not handling things well if you have two iTerm binaries on your system... which can happen :D

Can you please have a look at the code you have pasted in and update the two "tell" lines to be the location of your binary:
tell application \":Applications:iTerm.app\" (and note that you need to use a colon rather than a forward slash to delimit directories).

The reason I had to do this so explicitly was to get around issues where multiple iTerm binaries existed on the system (say concurrent versions, or even where someone had forgotten they had a second copy in their downloads folder) which would stop the integration working completely.

Please let me know if this resolves the issue for you.
Cheers,
Stuart

**Comment by vitorgalvao** [comment] 2015-10-02 17:49
Why the label “help wanted”? What do you need help with, here?

Tangentially, the issue being caused by the symlinking on homebrew-cask might be a problem now, [but won’t be one in the future](https://github.com/caskroom/homebrew-cask/issues/13201), so for homebrew-cask users this will solve itself.

**Comment by spry-rproud** [comment] 2015-10-05 14:50
I have no experience with AppleScript, but I threw this together.  Not sure if it's useful.

```applescript
on deSymlink(appAlias)
	set posixPath to POSIX path of appAlias
	try
		do shell script "[[ -L " & quoted form of posixPath & " ]]"
		return (do shell script "readlink " & posixPath)
	end try
	return appAlias
end deSymlink

log deSymlink(":Applications:iTerm.app")
```

**Comment by tucq88** [comment] 2015-11-03 16:30
I have installed iTerm by using **Homebrew-cask**. So iTerm was placed inside `~/Application` but it was just a symlink from its actual location inside `/opt/homebrew-cask/Caskroom/iterm`. 
So I update the script according to iTerm location and  this worked for me : 
```
...
tell application \":opt:homebrew-cask:Caskroom:iterm2:2.1.4:iTerm.app\"
...
```

**Comment by mattayes** [comment] 2016-03-24 16:28
I think this issue can be closed.

**Comment by stuartcryan** [comment] 2016-03-26 02:40
@spry-rproud 

Is that the code that you are using successfully on your computer at the moment, happy to look at integrating it in if so.

Kind Regards,
Stuart

**Comment by vitorgalvao** [comment] 2020-03-10 15:02
Issue seems to no longer be relevant, so closing. Please open a new issue if you still have this problem.

I’ll be introducing a new script version soon, so we’ll work from there to diagnose the problem if it still exists.

**Closed by vitorgalvao** 2020-03-10 15:02 UTC
